### ISSUE TITLE
desisim-testdata package name violates the "no hyphens" requirement

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim-testdata#1]
DESI package names should not contain contain hyphens, because `$DESISIM-TESTDATA` would be an invalid environment variable.

If this package will never actually be installed, or, equivalently, if it will never actually have a module file, then there is no need to change the name.

**Comment by sbailey** [comment]
This package was created to provide lightweight test data for testing desisim on Travis.  It is not intended to ever be installed at NERSC, though developers occasionally need to get their own copy and update it to make sure that it contains a complete set for all the tests in desisim.

i.e. I don't think it matters that it has a hyphen in it, but it could be replaced with an underscore.  Any renaming would need to be coordinated with an update to the desisim travis config.  I won't bother changing this unless the hyphen is actually creating a problem.

**Comment by weaverba137** [comment]
That's fine, I just wanted to make sure we were aware of this.
