### ISSUE TITLE
permission denied pushing new branch upstream

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim-testdata#2]
I ssh-cloned a copy of this repository, created a new branch, and made a bunch of changes.  But I don't seem to have permission to push my branch.  Am I doing something silly or is there a permission for this repository that needs to be set somewhere?  Thanks.

```
prometheus:desisim-testdata% git status
On branch add-sne
nothing to commit, working directory clean

prometheus:desisim-testdata% git push
fatal: The current branch add-sne has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin add-sne

prometheus:desisim-testdata% git push --set-upstream origin add-sne
ERROR: Permission to desihub/desisim-testdata.git denied to moustakas.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

prometheus:desisim-testdata% ssh git@github.com
Hi moustakas! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

**Comment by weaverba137** [comment]
When this repository was created, it was never added to the list of repositories that the 'developers' group has write access to.  This is fixed now.  Please try again.

Everyone, please remember to check the group permissions on repositories you create.  If you don't know how to do this, send mail to the desi-data mailing lists.

**Comment by moustakas** [comment]
Thanks @weaverba137 I'm all set.
